apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: 192.168.100.38:5002/google_containers/heapster:v1.1.0
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:http://192.168.100.35:8080?inClusterConfig=false&useServiceAccount=true&auth=
        - --sink=influxdb:http://monitoring-influxdb:8086
